// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HelloOKCode is the HTTP code returned for type HelloOK
const HelloOKCode int = 200

/*HelloOK Greeting content.

swagger:response helloOK
*/
type HelloOK struct {

	/*
	  In: Body
	*/
	Payload *HelloOKBody `json:"body,omitempty"`
}

// NewHelloOK creates HelloOK with default headers values
func NewHelloOK() *HelloOK {

	return &HelloOK{}
}

// WithPayload adds the payload to the hello o k response
func (o *HelloOK) WithPayload(payload *HelloOKBody) *HelloOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the hello o k response
func (o *HelloOK) SetPayload(payload *HelloOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HelloOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HelloInternalServerErrorCode is the HTTP code returned for type HelloInternalServerError
const HelloInternalServerErrorCode int = 500

/*HelloInternalServerError Internal Server Error - The server has encountered a situation it does not know how to handle.

swagger:response helloInternalServerError
*/
type HelloInternalServerError struct {
}

// NewHelloInternalServerError creates HelloInternalServerError with default headers values
func NewHelloInternalServerError() *HelloInternalServerError {

	return &HelloInternalServerError{}
}

// WriteResponse to the client
func (o *HelloInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
