name: Release workflow

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Version to produce"
        required: true
      release-as-draft:
        description: "Draft release"
        required: true
        type: boolean
        default: true
      release-as-prerelease:
        description: "Pre-release"
        required: true
        type: boolean
        default: false
      generate-release-notes:
        description: "Generate release notes"
        required: true
        type: boolean
        default: true

jobs:
  build-release:
    uses: ./.github/workflows/build.yml
    with:
      tag_name: ${{ github.event.inputs.release-version }}
      draft: ${{ github.event.inputs.release-as-draft }}
      prerelease: ${{ github.event.inputs.release-as-prerelease }}
      generate_release_notes: ${{ github.event.inputs.generate-release-notes }}
